--- #YAML:1.0
name:               AProf
version:            0.6
abstract:           is a profiler for periodically running processes
author:
    - Dmitry E. Oboukhov <unera@debian.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:         0
    Fcntl:        0
    Time::HiRes:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
